name: Deploy Helix

on:
  release:
    branches: [ master ]
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_SECRET }}